# Generated by Django 6.0.6 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
