# Generated by Django 6.0.1 on 2026-06-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_payment_status_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
