# Generated by Django 6.0.6 on 2026-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
