# Generated by Django 6.0.6 on 2026-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_deal_price_product_is_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
